---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mattflix-infra-ingress-nginx
  namespace: flux-system
spec:
  interval: 15m
  path: ./clusters/mattflix/infra/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
