---
version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "**"
    schedule:
      interval: "daily"
    assignees: 
      - "MattKobayashi"
    commit-message:
      prefix: "fix(deps)"
