---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mattflix-apps-plex
  namespace: flux-system
spec:
  interval: 15m
  path: ./clusters/mattflix/apps/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
