---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bl-apps
  namespace: flux-system
spec:
  path: ./clusters/binarylane/apps

  dependsOn:
    - name: bl-charts
    - name: bl-crds
    - name: bl-infra

  interval: 15m

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true
  validation: client

  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
