---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mattflix-infra-metallb-config
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: mattflix-infra-metallb-app
  path: ./clusters/mattflix/infra/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
