---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mattflix-infra
  namespace: flux-system
spec:
  path: ./clusters/mattflix/infra

  dependsOn:
    - name: mattflix-charts
    - name: mattflix-crds

  interval: 15m

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true
  validation: client

  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
