---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 15m
  values:

    controller:
      allowSnippetAnnotations: true

      # podAnnotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/port: '10254'

      replicaCount: 1

      service:
        type: LoadBalancer
        externalTrafficPolicy: Local

        ipFamilyPolicy: PreferDualStack

        ipFamilies:
          - IPv4
          - IPv6

        annotations:
          "lbipam.cilium.io/ips": "192.168.0.24"

      publishService:
        enabled: true

      config:
        enable-real-ip: true
        forwarded-for-header: proxy_protocol
        ssl-protocols: "TLSv1.3 TLSv1.2"
        custom-http-errors: 404,403,500,503
        enable-vts-status: "false"
        hsts-max-age: "31449600"
        proxy-body-size: "50m"

      resources:
        requests:
          memory: 250Mi
          cpu: 50m

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                topologyKey: kubernetes.io/hostname

    defaultBackend:
      enabled: false
      image:
        repository: ghcr.io/181192/custom-error-pages
        tag: latest

      resources:
        requests:
          memory: 250Mi
          cpu: 25m
